import 'dotenv/config';

export const env = {
  PORT: process.env.PORT,
  CORS_ORIGIN: process.env.CORS_ORIGIN,
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_URL: process.env.REDIS_URL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ROSSUM_API_KEY: process.env.ROSSUM_API_KEY,
  GOOGLE_DOC_AI_KEY: process.env.GOOGLE_DOC_AI_KEY,
  STRIPE_KEY: process.env.STRIPE_KEY,
  VIPPS_CLIENT_ID: process.env.VIPPS_CLIENT_ID,
  VIPPS_CLIENT_SECRET: process.env.VIPPS_CLIENT_SECRET,
  PEPPOL_ACCESS_POINT_API_KEY: process.env.PEPPOL_ACCESS_POINT_API_KEY,
  ELEVENLABS_API_KEY: process.env.ELEVENLABS_API_KEY,
  DEEPGRAM_API_KEY: process.env.DEEPGRAM_API_KEY,
  RUNWAY_API_KEY: process.env.RUNWAY_API_KEY,
  HEYGEN_API_KEY: process.env.HEYGEN_API_KEY,
  GOOGLE_SHEETS_ID: process.env.GOOGLE_SHEETS_ID,
  GOOGLE_CALENDAR_ID: process.env.GOOGLE_CALENDAR_ID,
  GOOGLE_SERVICE_ACCOUNT_JSON: process.env.GOOGLE_SERVICE_ACCOUNT_JSON
};
